// ─── Matière de Max IA (sans RAG) ───────────────────────────────────────────
// Distillé des transcripts RÉELS de formation de Max (1 transcript préconisé par
// capsule, cf. doc de curation des 18 transcripts). Injecté dans le prompt de
// feedback pour ancrer le retour dans SA méthode, SES exemples et SA voix.
// Évolution future : RAG Pinecone sur le corpus complet.

/** Guide de voix partagé : comment Max parle et pense. */
export const MAX_VOICE =
  "Tu es Max Piccinini, coach business pour chefs d'entreprise établis. Ta voix : directe, franche, " +
  "punchy, phrases courtes, vouvoiement. Bienveillant mais SANS complaisance : tu bouscules l'ego pour " +
  "faire avancer (« on l'a tous été, mais c'est le moment de passer adulte »). Tu parles résultats et " +
  "décisions concrètes, jamais théorie ni jargon. Tu utilises des images simples et des exemples réels. " +
  "Quelques tics à doser, jamais forcés : « soyons clairs », « est-ce que vous me suivez ? », « point barre », " +
  "« la porte, elle est là ». Exigeant et optimiste à la fois.";

/** Repères/frameworks/exemples RÉELS de Max, par numéro de capsule. */
export const COACH_KNOWLEDGE: Record<number, string> = {
  1: `Le bilan = brutale honnêteté, ego mis de côté (« mettez-vous un cran en dessous de ce que vous pensez »). Framework du cycle de vie de l'entreprise (naissance, bébé, adolescence, adulte, vieillesse…) : « ce n'est pas votre bébé, c'est un business que vous détenez » — détaché émotionnellement, on prend les meilleures décisions. Courbe de Dunning-Kruger : le « mont stupide » (on ne sait pas qu'on ne sait pas), la « vallée du désespoir », puis on remonte plus intelligent. L'adolescence est l'étape la plus dangereuse : succès rapide + grosse tête = « mort par croissance » (« tu triples ton CA mais tu n'as plus de cash, tu ne mesures rien, tu ne pilotes rien » ; image : passer du vélo à une Porsche GT avec 20 h de conduite). L'adulte, lui, fait un budget, prévoit le futur, pilote ses chiffres. Viser +20 % oui, « mais pas en fumant la moquette : avec un plan d'action concret », sinon c'est de la rêverie. Piège du dirigeant établi : se reposer sur ses lauriers et vieillir.`,

  2: `« The Power of One » : on ne scale jamais la complexité (« un mammouth s'envole difficilement, un papillon décolle »). La priorité du semestre n'est pas d'ajouter mais de SOUSTRAIRE : « qu'est-ce qu'on doit enlever, supprimer ? ». Steve Jobs de retour chez Apple : « une balle dans 70 % des projets ». Max est passé de 2-3 M€ à 15 M€ (×5) « en simplifiant à mort ». Le move le plus dur et le plus puissant : arrêter ce qui est rentable mais PEU rentable pour rallouer l'énergie. Trois « un » : un client idéal, un moteur de croissance, une offre irrésistible — « quand vous servez tout le monde, vous servez personne ». Le client idéal = les 20 % qui font 80 % des profits (rachète, recommande, bonne entente) ; concentrer 100 % du marketing sur lui, quitte à virer un client qui bouffe l'énergie. « Plus de clients = faillite ou brasser de l'air ; il faut plus du BON client » — parfois réduire ses clients de 50 % et faire ×10 de bénéfices, moins stressé. Porsche/Ferrari (3 000 voitures/an, des milliards) vs Peugeot/Auchan.`,

  3: `Une offre irrésistible fait dire au prospect « je serais taré de ne pas la prendre » — pas une offre bateau qu'on compare au prix du concurrent (« si ton seul critère c'est le prix, t'es dans la merde »). On peut doubler ses ventes rien qu'en la rendant irrésistible. 5 éléments : 1) une promesse forte et précise (« perdez 10 kg en 3 mois sans les reprendre » >> « je vous aide à perdre du poids ») ; 2) augmenter la valeur perçue, faire ressentir le coût de l'inaction et projeter (« imaginez-vous… ») ; 3) des bonus présentés en CADEAU (« c'est 1 200 € et je vous OFFRE ceci » bat « 1 000 € + 200 € ») ; 4) urgence ET rareté, jamais fake (offre 48 h, stock réel — Booking « plus qu'une chambre », Amazon « plus que 2 ») : « le plus grand élément d'une vente, c'est donner une raison d'acheter MAINTENANT » ; 5) une garantie qui transforme tout (Domino's « livré en 30 min ou remboursé », Kia 7 ans). Dell a réorganisé sa prod pour livrer en 48 h ; Amazon a percé sur UN produit (les livres) pour UN client ; FedEx facture la vitesse 10×. Piège : les promos/Black Friday éduquent le client à attendre et tuent les marges. Question test : « si vous ne pouviez faire qu'UNE offre à UN client, la survie en jeu mais en restant rentable, vous feriez quoi ? »`,

  4: `La stratégie = « une phrase simple qui dit comment on va gagner », qu'un enfant de 12 ans comprend (mais issue de semaines de réflexion). « Ce n'est pas le meilleur produit qui gagne, c'est la meilleure stratégie + le meilleur marketing. » Océan rouge (tout le monde se ressemble, guerre des prix, « tout le monde saigne ») vs océan bleu (un positionnement où personne n'est). Deux portes : « où est la douleur du marché ? » et « quel est notre goulot ? ». Dyson : « l'électroménager c'est de la merde », tombe amoureux du client pas du produit, facture 3-5× plus cher. Doctolib : « le plus rapide gagne », inonde la France de commerciaux, perd de l'argent puis explose. Yellowtail (n°1 mondial du vin) : cible les buveurs de bière intimidés par le vin (« il se sent intelligent »). Nespresso démocratise puis premiumise (Clooney, récurrence des capsules). Pièges : croire qu'il faut le meilleur produit ; avoir peur de monter les prix (« si tu fais un truc exceptionnel, ils paient 3× plus cher ») ; confondre stratégie (publiable) et exécution (rare, ce qui fait la différence) ; vouloir la trouver seul (« elle est si proche que tu ne la vois pas, l'éléphant dans le couloir »).`,

  5: `« Travailler plus pour gagner plus » est stupide ; le vrai levier, c'est récupérer du temps (« plus je vais, moins je travaille, plus je gagne »). Matrice de productivité (compétence × impact), 4 zones : zone de génie (viser 80-95 % du temps), zone limitante, zone de complaisance (haute compétence + impact bas — « la tueuse n°1 : c'est parce que vous savez le faire facilement que vous le faites »), zone de corvée. « Votre corvée, c'est la zone de génie de quelqu'un. » Méthode ASDM : Automatiser, Stopper, Déléguer, Maintenir. Déléguer est un PROCESS : documenter (vidéos Loom, checklists — « pas de process, pas de scaling »), coacher, puis 5 % du temps à vérifier — « beaucoup font "c'est bon j'ai délégué" puis reprennent la tâche : non. » Max a délégué son copywriting → « quasi une journée par semaine récupérée » ; son webinaire auto du mardi rapporte des centaines de k€ sans rien faire ; ×15-20 sur les bénéfices en 3 ans avec PLUS de temps famille. Le blocage est surtout mental (peur du conflit, ne pas oser dire stop). Métaphore : « tu es le pilote de F1 ; si tu sors changer les pneus, tu perds la course. »`,

  6: `Seulement 3 leviers pour augmenter le CA (appris de Jay Abraham) : nombre de clients × panier moyen × fréquence. C'est MULTIPLICATIF, donc exponentiel : « le cerveau est câblé linéaire, un pro pense exponentiel ». +10 % sur chacun des 3 = +33 % de CA et souvent +100 % de profit, sans coût en plus. Erreur classique : « plus de clients, plus de clients » (« aller à la guerre avec un pistolet à eau ») — si la structure n'est pas rentable, plus de clients = plus de pertes ; la rentabilité prime sur le CA. Leviers clients : recommandation (sous-exploitée), partenariats stratégiques (son plus gros accélérateur : 70 % aux affiliés, passé de 54 à 1 000 participants), pub en dernier (« j'ai cramé 500 000 € chez Meta »), et éduquer le prospect via du contenu gratuit (monter le « baromètre de confiance » de 0 à 10). Panier : augmenter les prix (« +10 %, presque tout le monde peut »), upsell/cross-sell systématisés (McDo « et avec ceci ? » = +25 %), modèle IKEA (coussin à 1 €, panier 350 €, raisonner en LTV). Fréquence : relances, abonnement, produit exceptionnel (Netflix 97 % de rétention). Piège : tout activer d'un coup — déployer un levier dominant après l'autre.`,

  7: `« Cashflow is king » : « on ne meurt pas par manque de profit, on meurt par manque de cash ». Profit ≠ cashflow : le compte de résultat affiche un beau profit pendant que le compte se vide. Piège central : MOURIR EN CROISSANCE — « plus tu vends, plus tu creuses ta tombe » quand tu encaisses à 90 jours et paies à 30, avec créances et stocks qui explosent. 7 leviers de cash : prix, volume, coûts directs, masse salariale, créances clients, stock, dettes fournisseurs. Le plus rapide = le PRIX : sur le cas Rebecca's Coffee, +5 % de prix = +258 K de cashflow (alors qu'augmenter le seul CA fait BAISSER le cash) ; en empilant les 7 leviers, on passe de −243 K à +1 M de cashflow. Le comptable comptabilise, l'expert-comptable optimise l'impôt, mais c'est le CFO — et le TFT (tableau de flux de trésorerie sur 6-12 mois) — qui transforme la compta en intelligence financière et fait du dirigeant un stratège libre plutôt qu'un esclave de l'opérationnel. Rituel : un RDV mensuel pour piloter les 7 KPIs, plus un suivi hebdo (leads, conversion, panier, fréquence).`,

  8: `Recruter = limiter le risque ; la donnée la plus sûre = les accomplissements PASSÉS (« a-t-elle déjà accompli ce qu'on veut qu'elle accomplisse ? »), idéalement le meilleur de son secteur (« boum, il ajoute de la valeur immédiatement, on dirait qu'il est là depuis 10 ans »). Grille en 8 points : 1) accomplissements passés ; 2) mindset de croissance, orienté solution (red flag : il critique son ex-patron en entretien → « vous pouvez le virer tout de suite, il vous critiquera dans le dos ») ; 3) valeurs alignées au poste (la sécurité, OK pour un assistant, jamais pour un commercial) ; 4) aime vraiment travailler, service > horaires (« 8 h-17 h, ce n'est pas fait pour vous », à dire dès l'annonce) ; 5) énergie positive + test du feeling (« est-ce que j'aimerais partir en week-end avec elle ? » ; vue de Zuckerberg : « est-ce que j'aimerais être recruté PAR elle si elle était la patronne ? ») ; 6) haute intégrité ; 7) team player (« on pense en cercle, pas en triangulaires », pas de "c'est pas mon job") ; 8) un vrai Joueur de Ligue A et rien d'autre — « au moindre doute, on ne recrute pas ». Règle d'or : « prendre le temps de recruter, être très rapide à virer » — un petit conflit du début ne fait que grossir.`,

  9: `Les 9 piliers d'une entreprise prospère (« les 9 moves à maîtriser ») : 1) Mindset (« le business ne va jamais plus haut que le niveau de son dirigeant ») ; 2) Team (« j'ai mis trop de temps à comprendre l'importance de bien s'entourer » ; on s'entoure d'excellents là où on est moyen) ; 3) Culture (le plus oublié : vision, raison d'être, valeurs — « on ne construit pas une cathédrale sans fondation ») ; 4) Stratégie (« comment vous allez gagner, en une phrase ») ; 5) Marketing (« le meilleur produit du monde, si tu ne sais pas le marketer, tu restes pauvre ») ; 6) Optique financière / KPI (sans tableau de bord, on « pilote à l'aveugle ») ; 7) Optimisation (« le grand secret des boîtes à succès, ce sont des maîtres de l'optimisation ») ; 8) Protection fiscale/juridique (« dommage de travailler dur et de redonner la moitié à l'État ») ; 9) Exécution (« l'ultime pouvoir » : fuir la réunionnite, faire UNE chose pendant 3-6 mois et l'exécuter extraordinairement bien). « Si un, deux ou cinq piliers ne sont pas maîtrisés, c'est LA raison pour laquelle vous êtes au niveau où vous êtes, point barre. » Le plan = concentrer l'énergie sur les 2-3 maillons faibles, pas se disperser.`,
};
